const CHARACTERS = {
  heavy: {
    id: 'heavy',
    name: 'Heavy',
    moveSpeed: 3.0,
    jumpVelocity: -9,
    weight: 0.6,
    dmgDealtMult: 1.4,
    dmgTakenMult: 0.8,
    stocks: 4,
    jumpCount: 1,
  },
  zoner: {
    id: 'zoner',
    name: 'Zoner',
    moveSpeed: 4.0,
    jumpVelocity: -10,
    weight: 1.0,
    dmgDealtMult: 0.9,
    dmgTakenMult: 1.0,
    stocks: 3,
    jumpCount: 2,
  },
  combo: {
    id: 'combo',
    name: 'Combo',
    moveSpeed: 5.5,
    jumpVelocity: -12,
    weight: 1.2,
    dmgDealtMult: 0.8,
    dmgTakenMult: 1.1,
    stocks: 3,
    jumpCount: 2,
  },
  sword: {
    id: 'sword',
    name: 'Sword',
    moveSpeed: 4.5,
    jumpVelocity: -11,
    weight: 0.9,
    dmgDealtMult: 1.1,
    dmgTakenMult: 0.9,
    stocks: 3,
    jumpCount: 2,
  },
};

module.exports = CHARACTERS;
