export const CHARACTERS = {
  heavy: {
    id: 'heavy',
    name: 'Heavy',
    description: 'Slow, tanky, huge damage.',
    color: 0xff4444,
    tint: 0xff6666,
    moveSpeed: 3.0,
    jumpVelocity: -9,
    weight: 0.6,
    dmgDealtMult: 1.4,
    dmgTakenMult: 0.8,
    stocks: 4,
    jumpCount: 1,
  },
  zoner: {
    id: 'zoner',
    name: 'Zoner',
    description: 'Long-range attacks, controls space.',
    color: 0x44ff44,
    tint: 0x66ff66,
    moveSpeed: 4.0,
    jumpVelocity: -10,
    weight: 1.0,
    dmgDealtMult: 0.9,
    dmgTakenMult: 1.0,
    stocks: 3,
    jumpCount: 2,
  },
  combo: {
    id: 'combo',
    name: 'Combo',
    description: 'Fast, mobile, long combos.',
    color: 0xffff44,
    tint: 0xffff66,
    moveSpeed: 5.5,
    jumpVelocity: -12,
    weight: 1.2,
    dmgDealtMult: 0.8,
    dmgTakenMult: 1.1,
    stocks: 3,
    jumpCount: 2,
  },
  sword: {
    id: 'sword',
    name: 'Sword',
    description: 'Strong range and spacing, balanced.',
    color: 0x4488ff,
    tint: 0x66aaff,
    moveSpeed: 4.5,
    jumpVelocity: -11,
    weight: 0.9,
    dmgDealtMult: 1.1,
    dmgTakenMult: 0.9,
    stocks: 3,
    jumpCount: 2,
  },
};

export const CHARACTER_LIST = Object.values(CHARACTERS);
